//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pic.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PICTYPE                     129
#define IDD_PREVIEW_TOOLBAR             130
#define IDD_SETTING                     131
#define IDD_TH                          131
#define IDD_COLOR                       132
#define IDD_AFFINE                      133
#define IDB_BITMAP1                     134
#define IDD_MORPH                       135
#define IDD_LP                          137
#define IDD_COLOR1                      138
#define IDD_AFFINE1                     140
#define IDD_GABOR2                      141
#define IDD_TH2                         142
#define IDD_HOUGH                       143
#define IDD_HLAC                        144
#define IDD_RLP                         145
#define IDD_FACE_RECOGNITION            146
#define IDD_SOFT_COMPUTING              147
#define IDD_PROJECTION                  149
#define IDD_EDGE                        150
#define IDD_HIST                        152
#define IDC_MIN_TH                      1003
#define IDC_MAX_TH                      1004
#define IDC_INSIDE                      1005
#define IDC_GREAT                       1006
#define IDC_LESS                        1007
#define IDC_OUTSIDE                     1008
#define IDC_ANG                         1012
#define IDC_ZX                          1013
#define IDC_HLS                         1013
#define IDC_PX                          1014
#define IDC_RGB                         1014
#define IDC_MORPH                       1014
#define IDC_ZY                          1015
#define IDC_YIQ                         1015
#define IDC_RADIO2                      1015
#define IDC_PY                          1016
#define IDC_IRG                         1016
#define IDC_RADIO3                      1016
#define IDC_WAVE                        1016
#define IDC_LIRG                        1017
#define IDC_RADIO4                      1017
#define IDC_THETA                       1017
#define IDC_EMIN                        1017
#define IDC_RGB2                        1018
#define IDC_RADIO5                      1018
#define IDC_EMAX                        1018
#define IDC_HLS2                        1019
#define IDC_RADIO6                      1019
#define IDC_UH                          1019
#define IDC_VV                          1020
#define IDC_RADIO1                      1020
#define IDC_HLS3                        1020
#define IDC_RADIO7                      1021
#define IDC_ANGLE                       1021
#define IDC_HLS4                        1021
#define IDC_METHOD                      1021
#define IDC_RADIO8                      1022
#define IDC_TH                          1022
#define IDC_U                           1022
#define IDC_HLS5                        1022
#define IDC_RADIO9                      1023
#define IDC_V                           1023
#define IDC_RGB3                        1023
#define IDC_RADIO10                     1024
#define IDC_XF                          1024
#define IDC_W                           1024
#define IDC_HLS6                        1024
#define IDC_RADIO11                     1025
#define IDC_YF                          1025
#define IDC_H                           1025
#define IDC_HLS7                        1025
#define IDC_WAVE2                       1025
#define IDC_RADIO12                     1026
#define IDC_HLS8                        1026
#define IDC_RADIO13                     1027
#define IDC_HLS9                        1027
#define IDC_RGB4                        1028
#define IDC_RADIO15                     1028
#define IDC_RADIO14                     1029
#define IDC_NF                          1029
#define IDC_RADIO16                     1029
#define IDC_NNF                         1030
#define IDC_MR                          1030
#define IDC_RADIO17                     1030
#define IDC_SRR                         1031
#define IDC_RADIO18                     1031
#define IDC_MG                          1032
#define IDC_RADIO19                     1032
#define IDC_SGG                         1033
#define IDC_RADIO20                     1033
#define IDC_R                           1034
#define IDC_G                           1035
#define IDC_B                           1036
#define IDC_EDIT1                       1036
#define IDC_ALL                         1037
#define IDC_EDIT2                       1037
#define IDC_EDIT3                       1038
#define IDC_XDIR                        1040
#define IDC_YDIR                        1041
#define IDC_WEIGHT                      1042
#define IDC_KERNEL                      1042
#define IDC_WEIGHT2                     1043
#define IDC_P1                          1043
#define IDC_P2                          1044
#define IDC_OTSU_P                      1046
#define IDM_LOWPASS                     32771
#define IDM_HIGHPASS                    32772
#define IDM_BOUNDARY                    32773
#define IDM_EMBOSSING                   32774
#define IDM_INVERT                      32776
#define ID_FACE_LFT                     32777
#define ID_ADJUST_THRESHOLD             32778
#define ID_FACE_LP                      32779
#define ID_FILTER_HLAC                  32780
#define ID_ROTATE_AFFINE                32781
#define ID_FACE_COLOR                   32782
#define ID_FACE_RCER                    32783
#define ID_FILTERING_MORP               32784
#define ID_FILT_HE                      32785
#define ID_FILT_VE                      32786
#define ID_FILTERING_DEDGE              32787
#define ID_FILT_PROJ                    32788
#define ID_MOMENT_FEATURE               32789
#define ID_FACE_GABOR                   32790
#define ID_HOUGH                        32791
#define ID_FACE_FIND                    32792
#define ID_FACE_RLP                     32793
#define ID_FACE_LPCENTER                32794
#define ID_FACE_NN                      32795
#define ID_FACE_FL                      32796
#define ID_FACE_COLOR_SPEC              32797
#define ID_DYNAMIC_INPUT                32798
#define ID_DYNAMIC_CAPTURE              32799
#define ID_DYNAMIC_OPT                  32800
#define ID_FACE_COMP                    32801
#define ID_EDIT_POINT                   32802
#define ID_FACE_STUDY                   32803
#define ID_DYNAMIC_EDGE                 32805
#define ID_DYNAMIC_MOTION               32806
#define ID_DYNAMIC_VIEW                 32807
#define ID_DYNAMIC_WHITE                32808
#define ID_DYNAMIC_FACE                 32809
#define ID_DYNAMIC_BACKGND              32810
#define ID_VIEW_BLOB                    32811
#define IDM_BRIGHT                      32812
#define IDM_DARK                        32813
#define IDM_CONTRAST                    32814
#define ID_VIEW_WHITE                   32816
#define ID_DYNAMIC_CAM_SELECT           32817
#define ID_DYNAMIC_CAM_SETTING          32818
#define ID_DYNAMIC_GETBACK              32819
#define ID_FILT_EDGE                    32820
#define ID_FILT_HISTO                   32821
#define ID_FACE_DTM                     32822
#define ID_DYNAMIC_OFF                  32823
#define ID_FACE_CT21_4                  32824
#define ID_EDIT_JINWOO                  32825
#define ID_HS_TEST                      32826
#define IDM_REGIONSELECT                32829
#define IDM_CONTRASTDOWN                32831
#define IDM_TURNRIGHT                   32832
#define IDM_TURNLEFT                    32833
#define IDM_TURNVERTICAL                32834
#define IDM_TURNHORIZONTAL              32835
#define IDM_DUPLICATE                   32837
#define ID_MAG2                         32842
#define ID_MAG4                         32843
#define ID_MAG8                         32844
#define ID_MAGN2                        32845
#define ID_MAGN4                        32846
#define ID_MAGN8                        32847
#define ID_ORIGINALSIZE                 32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
