//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SoftComputingWnd.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SOFTCOTYPE                  129
#define IDD_CMD_COLOR                   132
#define IDD_CMD_FILTER                  134
#define IDD_CMD_FTX                     136
#define IDD_CMD_BLOB                    138
#define IDD_CMD_SF                      141
#define IDD_CMD_GF                      142
#define IDD_CMD_TEMPLATE_MATCHING       143
#define IDD_CMD_PROJ_EXT                144
#define IDD_CMD_COORD                   145
#define IDD_CMD_THRESHOLD               151
#define IDD_VERIFY                      154
#define IDD_CMD_ALU                     155
#define IDD_CMD_NN                      157
#define IDD_CMD_FMMNN                   159
#define IDD_CMD_FNN                     163
#define IDD_CMD_EIGEN                   165
#define IDC_SOURCE                      1004
#define IDC_RESULT                      1005
#define IDC_FILTERING_METHOD            1005
#define IDC_ACT_CONVERT                 1006
#define IDC_ACT_FILTERING               1007
#define IDC_BUTTON1                     1009
#define IDC_FOURIER                     1010
#define IDC_COORD_TX                    1011
#define IDC_SRC_COORD                   1012
#define IDC_TAR_COORD                   1013
#define IDC_BLOB_ANAL                   1013
#define IDC_BLOB_METHOD                 1014
#define IDC_PROJ_EX                     1015
#define IDC_TEMP_MATCH                  1016
#define IDC_TM_METHOD                   1017
#define IDC_GF_EXT                      1018
#define IDC_TM_METHOD2                  1018
#define IDC_GF_GLOBAL                   1019
#define IDC_GF_LOCAL                    1020
#define IDC_SF_EXT                      1021
#define IDC_SF_FEAT                     1022
#define IDC_ACT_TH                      1023
#define IDC_MIN_TH                      1024
#define IDC_MAX_TH                      1025
#define IDC_TH_METHOD                   1026
#define IDC_MAX_THR                     1027
#define IDC_MIN_THR                     1028
#define IDC_PROJ_DIR                    1028
#define IDC_MORPH                       1029
#define IDC_MORPH_NUM                   1030
#define IDC_LOW_TH                      1031
#define IDC_HIGH_TH                     1032
#define IDC_LOW_TH_VAL                  1033
#define IDC_HIGH_TH_VAL                 1034
#define IDC_ACT_VER                     1034
#define IDC_FACE_VER_VAL                1035
#define IDC_GABOR_ANGLE                 1035
#define IDC_FACE_VER                    1036
#define IDC_GABOR_ANGLE_VAL             1036
#define IDC_LEFT_EYEB                   1037
#define IDC_GABOR_WAVE                  1037
#define IDC_RIGHT_EYEB                  1038
#define IDC_GABOR_WAVE_VAL              1038
#define IDC_NOSE                        1039
#define IDC_MOUTH                       1040
#define IDC_MATCH_DEGREE                1040
#define IDC_FOREHEAD                    1041
#define IDC_MATCH_DEGREE_VAL            1041
#define IDC_INTERDIST                   1042
#define IDC_INTERNM                     1043
#define IDC_JAW                         1044
#define IDC_ACT_ALU                     1045
#define IDC_OPERATOR                    1046
#define IDC_CHECK1                      1047
#define IDC_CHECK2                      1048
#define IDC_CHECK3                      1049
#define IDC_CONST                       1050
#define IDC_NN_METHOD                   1053
#define IDC_FMMNN_R                     1054
#define IDC_REC_FMMNN                   1055
#define IDC_NN_ERR                      1055
#define IDC_FMMNN_THETA                 1056
#define IDC_REC_NN                      1058
#define IDC_FMMNN_METHOD                1059
#define IDC_NN_EP                       1060
#define IDC_NN_LR                       1061
#define IDC_NN_MO                       1062
#define IDC_FNN_METHOD                  1063
#define IDC_REC_FNN                     1064
#define IDC_FNN_SP1                     1065
#define IDC_FNN_SP2                     1066
#define IDC_FNN_EP                      1067
#define IDC_FNN_ERR                     1068
#define IDC_FNN_LR                      1069
#define IDC_REC_EIGEN                   1070
#define IDC_EIGEN_METHOD                1071
#define IDC_EIGEN_EP                    1072
#define IDC_EIGEN_ERR                   1073
#define ID_IMG_FILTERING                32777
#define ID_COLOR_CONVERSION             32778
#define ID_COORD_TX                     32779
#define ID_TEMPLATE_MATCHING            32780
#define ID_BLOB_ANAL                    32781
#define ID_COMP_TEMPLATE                32783
#define ID_PROJ_EXT                     32784
#define ID_GEO_EST                      32785
#define ID_GEO_FEAT                     32786
#define ID_FOU_TX                       32787
#define ID_STAT_FEAT                    32788
#define ID_PRE_TH                       32789
#define ID_VIEW_MAG                     32790
#define ID_VIEW_SELECT                  32791
#define ID_RAW_ALU                      32792
#define ID_EIGENFACE                    32793
#define ID_FNN_CLS                      32794
#define ID_NN_CLS                       32795
#define ID_FMMNN_CLS                    32796
#define ID_VIDEO_CAMONOFF               32797
#define ID_VIDEO_CAMFORMAT              32798
#define ID_VIDEO_CAMSETTING             32799
#define ID_VIDEO_FACEDETECT             32800
#define ID_VIDEO_FACIALFEATURE          32801
#define ID_VIDEO_FEREC                  32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
